error:
  E20001: "(500) Request stream met io exception: {0}"
  E20002: "(500) Request body format is invalid, could not be convert to {0}"
  E20003: "(400) Request body is required, but now it''s missing. name = {0}, method = {1}"
  E20004: "(400) Validation failure occurs, field = {0}, value = {1}, rule = {2}, config = {3}"
  E20005: "(500) Could not write JSON: {0}"
  E20006: "(409) Up framework met concurrency failure exception, message = {0}, source = {1}"
  E20007: "(400) Common bad request met, detail = {0}"
  E20008: "(404) Could not find such element, message = {0}, source = {1}"
  E20009: "(500) The input parameter ''{0}'' is not valid URI, there are some syntax error."
  E20010: "(500) System detect error when build response here. message = {0}, source = {1}"
  E20011: "(401) User {0} was not found in the database"
  E20012: "(401) User {0} was inactivated, please unlock this account first"
  E20013: "(401) Current operation support unique authority only, but user {0} found {1} authorities, duplicated"
  E20014: "(401) You have used \"spring-up\" authority expression method, Current error raw = {0}"
  E20015: "(500) Server internal error met, details = {0}"
  E20016: "(424) Remote method on address {0} could not be found"
  E20017: "(424) The invoker for method \"{0}\" could not be found"
  E20018: "(500) Your code execute met error: {0}"
  E20019: "(400) Could not get responser for type : {0}"
  E20020: "(401) The system could not get the data from UAA: {0}, the body is null or format invalid, details = {1}."
  E20021: "(401) Could not get the token from UAA: {0}, some error occurs {1}."
  # Query
  E60022: "(400) [QE] You''ll try to parse Ir key = \"{0}\", the expected type is {1} but now it''s {2}"
  E60023: "(400) [QE] You''ll try to build \"pager\", the key \"{0}\" of pager missing."
  E60024: "(500) [QE] Query metadata must not be null"
  E60025: "(500) [IPC] Your method signature is invalid, is support `JsonObject m(JsonObject)` & `Envelop m(Envelop)`. method = {0}, clazz = {1}"
  E60026: "(400) - (Ir) The op is not supported, please provide valid op of \"<, >, <=, >=, =, <>, !n, n, t, f, i, !i, s, e, c\", current is {0}"
  # Plugin
  E30001: "(500) ( Sms ) Plugin key \"{0}\" is missing, it''s required."
