// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.envelop.proto

package io.spring.up.ipc.model;

/**
 * Protobuf type {@code io.spring.up.ipc.model.IpcEnvelop}
 */
public  final class IpcEnvelop extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.spring.up.ipc.model.IpcEnvelop)
    IpcEnvelopOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IpcEnvelop.newBuilder() to construct.
  private IpcEnvelop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IpcEnvelop() {
    type_ = 0;
    body_ = "";
    stream_ = com.google.protobuf.ByteString.EMPTY;
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IpcEnvelop();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IpcEnvelop(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            body_ = s;
            break;
          }
          case 26: {

            stream_ = input.readBytes();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.spring.up.ipc.model.UpEnvelop.internal_static_io_spring_up_ipc_model_IpcEnvelop_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.spring.up.ipc.model.UpEnvelop.internal_static_io_spring_up_ipc_model_IpcEnvelop_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.spring.up.ipc.model.IpcEnvelop.class, io.spring.up.ipc.model.IpcEnvelop.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   * Envelop data format
   * </pre>
   *
   * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Envelop data format
   * </pre>
   *
   * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
   * @return The type.
   */
  public io.spring.up.ipc.model.em.Format getType() {
    @SuppressWarnings("deprecation")
    io.spring.up.ipc.model.em.Format result = io.spring.up.ipc.model.em.Format.valueOf(type_);
    return result == null ? io.spring.up.ipc.model.em.Format.UNRECOGNIZED : result;
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private volatile java.lang.Object body_;
  /**
   * <pre>
   * Body content
   * </pre>
   *
   * <code>string body = 2;</code>
   * @return The body.
   */
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Body content
   * </pre>
   *
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREAM_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString stream_;
  /**
   * <pre>
   * Stream content
   * </pre>
   *
   * <code>bytes stream = 3;</code>
   * @return The stream.
   */
  public com.google.protobuf.ByteString getStream() {
    return stream_;
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Service name for method calling, connect to method
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Service name for method calling, connect to method
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != io.spring.up.ipc.model.em.Format.BINARY.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!getBodyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
    }
    if (!stream_.isEmpty()) {
      output.writeBytes(3, stream_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != io.spring.up.ipc.model.em.Format.BINARY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!getBodyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
    }
    if (!stream_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, stream_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.spring.up.ipc.model.IpcEnvelop)) {
      return super.equals(obj);
    }
    io.spring.up.ipc.model.IpcEnvelop other = (io.spring.up.ipc.model.IpcEnvelop) obj;

    if (type_ != other.type_) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getStream()
        .equals(other.getStream())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + STREAM_FIELD_NUMBER;
    hash = (53 * hash) + getStream().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.spring.up.ipc.model.IpcEnvelop parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.spring.up.ipc.model.IpcEnvelop prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.spring.up.ipc.model.IpcEnvelop}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.spring.up.ipc.model.IpcEnvelop)
      io.spring.up.ipc.model.IpcEnvelopOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.spring.up.ipc.model.UpEnvelop.internal_static_io_spring_up_ipc_model_IpcEnvelop_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.spring.up.ipc.model.UpEnvelop.internal_static_io_spring_up_ipc_model_IpcEnvelop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.spring.up.ipc.model.IpcEnvelop.class, io.spring.up.ipc.model.IpcEnvelop.Builder.class);
    }

    // Construct using io.spring.up.ipc.model.IpcEnvelop.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      body_ = "";

      stream_ = com.google.protobuf.ByteString.EMPTY;

      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.spring.up.ipc.model.UpEnvelop.internal_static_io_spring_up_ipc_model_IpcEnvelop_descriptor;
    }

    @java.lang.Override
    public io.spring.up.ipc.model.IpcEnvelop getDefaultInstanceForType() {
      return io.spring.up.ipc.model.IpcEnvelop.getDefaultInstance();
    }

    @java.lang.Override
    public io.spring.up.ipc.model.IpcEnvelop build() {
      io.spring.up.ipc.model.IpcEnvelop result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.spring.up.ipc.model.IpcEnvelop buildPartial() {
      io.spring.up.ipc.model.IpcEnvelop result = new io.spring.up.ipc.model.IpcEnvelop(this);
      result.type_ = type_;
      result.body_ = body_;
      result.stream_ = stream_;
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.spring.up.ipc.model.IpcEnvelop) {
        return mergeFrom((io.spring.up.ipc.model.IpcEnvelop)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.spring.up.ipc.model.IpcEnvelop other) {
      if (other == io.spring.up.ipc.model.IpcEnvelop.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        onChanged();
      }
      if (other.getStream() != com.google.protobuf.ByteString.EMPTY) {
        setStream(other.getStream());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.spring.up.ipc.model.IpcEnvelop parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.spring.up.ipc.model.IpcEnvelop) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * Envelop data format
     * </pre>
     *
     * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Envelop data format
     * </pre>
     *
     * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Envelop data format
     * </pre>
     *
     * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
     * @return The type.
     */
    public io.spring.up.ipc.model.em.Format getType() {
      @SuppressWarnings("deprecation")
      io.spring.up.ipc.model.em.Format result = io.spring.up.ipc.model.em.Format.valueOf(type_);
      return result == null ? io.spring.up.ipc.model.em.Format.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Envelop data format
     * </pre>
     *
     * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(io.spring.up.ipc.model.em.Format value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Envelop data format
     * </pre>
     *
     * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <pre>
     * Body content
     * </pre>
     *
     * <code>string body = 2;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Body content
     * </pre>
     *
     * <code>string body = 2;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Body content
     * </pre>
     *
     * <code>string body = 2;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Body content
     * </pre>
     *
     * <code>string body = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Body content
     * </pre>
     *
     * <code>string body = 2;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      body_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString stream_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Stream content
     * </pre>
     *
     * <code>bytes stream = 3;</code>
     * @return The stream.
     */
    public com.google.protobuf.ByteString getStream() {
      return stream_;
    }
    /**
     * <pre>
     * Stream content
     * </pre>
     *
     * <code>bytes stream = 3;</code>
     * @param value The stream to set.
     * @return This builder for chaining.
     */
    public Builder setStream(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stream_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Stream content
     * </pre>
     *
     * <code>bytes stream = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStream() {
      
      stream_ = getDefaultInstance().getStream();
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Service name for method calling, connect to method
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Service name for method calling, connect to method
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Service name for method calling, connect to method
     * </pre>
     *
     * <code>string name = 4;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Service name for method calling, connect to method
     * </pre>
     *
     * <code>string name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Service name for method calling, connect to method
     * </pre>
     *
     * <code>string name = 4;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.spring.up.ipc.model.IpcEnvelop)
  }

  // @@protoc_insertion_point(class_scope:io.spring.up.ipc.model.IpcEnvelop)
  private static final io.spring.up.ipc.model.IpcEnvelop DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.spring.up.ipc.model.IpcEnvelop();
  }

  public static io.spring.up.ipc.model.IpcEnvelop getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IpcEnvelop>
      PARSER = new com.google.protobuf.AbstractParser<IpcEnvelop>() {
    @java.lang.Override
    public IpcEnvelop parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IpcEnvelop(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IpcEnvelop> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IpcEnvelop> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.spring.up.ipc.model.IpcEnvelop getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

