// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.envelop.proto

package io.spring.up.ipc.model;

public interface IpcEnvelopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.spring.up.ipc.model.IpcEnvelop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Envelop data format
   * </pre>
   *
   * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Envelop data format
   * </pre>
   *
   * <code>.io.spring.up.ipc.model.em.Format type = 1;</code>
   * @return The type.
   */
  io.spring.up.ipc.model.em.Format getType();

  /**
   * <pre>
   * Body content
   * </pre>
   *
   * <code>string body = 2;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <pre>
   * Body content
   * </pre>
   *
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <pre>
   * Stream content
   * </pre>
   *
   * <code>bytes stream = 3;</code>
   * @return The stream.
   */
  com.google.protobuf.ByteString getStream();

  /**
   * <pre>
   * Service name for method calling, connect to method
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Service name for method calling, connect to method
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
