// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.envelop.proto

package io.spring.up.ipc.model;

public interface IpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.spring.up.ipc.model.IpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Response content
   * </pre>
   *
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   * @return Whether the envelop field is set.
   */
  boolean hasEnvelop();
  /**
   * <pre>
   * Response content
   * </pre>
   *
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   * @return The envelop.
   */
  io.spring.up.ipc.model.IpcEnvelop getEnvelop();
  /**
   * <pre>
   * Response content
   * </pre>
   *
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   */
  io.spring.up.ipc.model.IpcEnvelopOrBuilder getEnvelopOrBuilder();

  /**
   * <pre>
   * Passed client id
   * </pre>
   *
   * <code>string client_id = 2;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Passed client id
   * </pre>
   *
   * <code>string client_id = 2;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   * Passed scope
   * </pre>
   *
   * <code>string oauth_scope = 3;</code>
   * @return The oauthScope.
   */
  java.lang.String getOauthScope();
  /**
   * <pre>
   * Passed scope
   * </pre>
   *
   * <code>string oauth_scope = 3;</code>
   * @return The bytes for oauthScope.
   */
  com.google.protobuf.ByteString
      getOauthScopeBytes();
}
