// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.status.proto

package io.spring.up.ipc.model;

public interface RetryParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.spring.up.ipc.model.RetryParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Retry
   * </pre>
   *
   * <code>int32 max_reconnect = 1;</code>
   * @return The maxReconnect.
   */
  int getMaxReconnect();
}
