// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.stream.proto

package io.spring.up.ipc.model;

public interface StreamClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.spring.up.ipc.model.StreamClientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 aggregated_size = 1;</code>
   * @return The aggregatedSize.
   */
  int getAggregatedSize();
}
