// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.stream.proto

package io.spring.up.ipc.model;

public interface StreamServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.spring.up.ipc.model.StreamServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   * @return Whether the envelop field is set.
   */
  boolean hasEnvelop();
  /**
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   * @return The envelop.
   */
  io.spring.up.ipc.model.IpcEnvelop getEnvelop();
  /**
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   */
  io.spring.up.ipc.model.IpcEnvelopOrBuilder getEnvelopOrBuilder();
}
