// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.stream.proto

package io.spring.up.ipc.model;

/**
 * Protobuf type {@code io.spring.up.ipc.model.StreamServerResponse}
 */
public  final class StreamServerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.spring.up.ipc.model.StreamServerResponse)
    StreamServerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamServerResponse.newBuilder() to construct.
  private StreamServerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamServerResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamServerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamServerResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.spring.up.ipc.model.IpcEnvelop.Builder subBuilder = null;
            if (envelop_ != null) {
              subBuilder = envelop_.toBuilder();
            }
            envelop_ = input.readMessage(io.spring.up.ipc.model.IpcEnvelop.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(envelop_);
              envelop_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.spring.up.ipc.model.UpStream.internal_static_io_spring_up_ipc_model_StreamServerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.spring.up.ipc.model.UpStream.internal_static_io_spring_up_ipc_model_StreamServerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.spring.up.ipc.model.StreamServerResponse.class, io.spring.up.ipc.model.StreamServerResponse.Builder.class);
  }

  public static final int ENVELOP_FIELD_NUMBER = 1;
  private io.spring.up.ipc.model.IpcEnvelop envelop_;
  /**
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   * @return Whether the envelop field is set.
   */
  public boolean hasEnvelop() {
    return envelop_ != null;
  }
  /**
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   * @return The envelop.
   */
  public io.spring.up.ipc.model.IpcEnvelop getEnvelop() {
    return envelop_ == null ? io.spring.up.ipc.model.IpcEnvelop.getDefaultInstance() : envelop_;
  }
  /**
   * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
   */
  public io.spring.up.ipc.model.IpcEnvelopOrBuilder getEnvelopOrBuilder() {
    return getEnvelop();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (envelop_ != null) {
      output.writeMessage(1, getEnvelop());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (envelop_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEnvelop());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.spring.up.ipc.model.StreamServerResponse)) {
      return super.equals(obj);
    }
    io.spring.up.ipc.model.StreamServerResponse other = (io.spring.up.ipc.model.StreamServerResponse) obj;

    if (hasEnvelop() != other.hasEnvelop()) return false;
    if (hasEnvelop()) {
      if (!getEnvelop()
          .equals(other.getEnvelop())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEnvelop()) {
      hash = (37 * hash) + ENVELOP_FIELD_NUMBER;
      hash = (53 * hash) + getEnvelop().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.spring.up.ipc.model.StreamServerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.spring.up.ipc.model.StreamServerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.spring.up.ipc.model.StreamServerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.spring.up.ipc.model.StreamServerResponse)
      io.spring.up.ipc.model.StreamServerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.spring.up.ipc.model.UpStream.internal_static_io_spring_up_ipc_model_StreamServerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.spring.up.ipc.model.UpStream.internal_static_io_spring_up_ipc_model_StreamServerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.spring.up.ipc.model.StreamServerResponse.class, io.spring.up.ipc.model.StreamServerResponse.Builder.class);
    }

    // Construct using io.spring.up.ipc.model.StreamServerResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (envelopBuilder_ == null) {
        envelop_ = null;
      } else {
        envelop_ = null;
        envelopBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.spring.up.ipc.model.UpStream.internal_static_io_spring_up_ipc_model_StreamServerResponse_descriptor;
    }

    @java.lang.Override
    public io.spring.up.ipc.model.StreamServerResponse getDefaultInstanceForType() {
      return io.spring.up.ipc.model.StreamServerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.spring.up.ipc.model.StreamServerResponse build() {
      io.spring.up.ipc.model.StreamServerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.spring.up.ipc.model.StreamServerResponse buildPartial() {
      io.spring.up.ipc.model.StreamServerResponse result = new io.spring.up.ipc.model.StreamServerResponse(this);
      if (envelopBuilder_ == null) {
        result.envelop_ = envelop_;
      } else {
        result.envelop_ = envelopBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.spring.up.ipc.model.StreamServerResponse) {
        return mergeFrom((io.spring.up.ipc.model.StreamServerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.spring.up.ipc.model.StreamServerResponse other) {
      if (other == io.spring.up.ipc.model.StreamServerResponse.getDefaultInstance()) return this;
      if (other.hasEnvelop()) {
        mergeEnvelop(other.getEnvelop());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.spring.up.ipc.model.StreamServerResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.spring.up.ipc.model.StreamServerResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.spring.up.ipc.model.IpcEnvelop envelop_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.spring.up.ipc.model.IpcEnvelop, io.spring.up.ipc.model.IpcEnvelop.Builder, io.spring.up.ipc.model.IpcEnvelopOrBuilder> envelopBuilder_;
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     * @return Whether the envelop field is set.
     */
    public boolean hasEnvelop() {
      return envelopBuilder_ != null || envelop_ != null;
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     * @return The envelop.
     */
    public io.spring.up.ipc.model.IpcEnvelop getEnvelop() {
      if (envelopBuilder_ == null) {
        return envelop_ == null ? io.spring.up.ipc.model.IpcEnvelop.getDefaultInstance() : envelop_;
      } else {
        return envelopBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     */
    public Builder setEnvelop(io.spring.up.ipc.model.IpcEnvelop value) {
      if (envelopBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        envelop_ = value;
        onChanged();
      } else {
        envelopBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     */
    public Builder setEnvelop(
        io.spring.up.ipc.model.IpcEnvelop.Builder builderForValue) {
      if (envelopBuilder_ == null) {
        envelop_ = builderForValue.build();
        onChanged();
      } else {
        envelopBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     */
    public Builder mergeEnvelop(io.spring.up.ipc.model.IpcEnvelop value) {
      if (envelopBuilder_ == null) {
        if (envelop_ != null) {
          envelop_ =
            io.spring.up.ipc.model.IpcEnvelop.newBuilder(envelop_).mergeFrom(value).buildPartial();
        } else {
          envelop_ = value;
        }
        onChanged();
      } else {
        envelopBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     */
    public Builder clearEnvelop() {
      if (envelopBuilder_ == null) {
        envelop_ = null;
        onChanged();
      } else {
        envelop_ = null;
        envelopBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     */
    public io.spring.up.ipc.model.IpcEnvelop.Builder getEnvelopBuilder() {
      
      onChanged();
      return getEnvelopFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     */
    public io.spring.up.ipc.model.IpcEnvelopOrBuilder getEnvelopOrBuilder() {
      if (envelopBuilder_ != null) {
        return envelopBuilder_.getMessageOrBuilder();
      } else {
        return envelop_ == null ?
            io.spring.up.ipc.model.IpcEnvelop.getDefaultInstance() : envelop_;
      }
    }
    /**
     * <code>.io.spring.up.ipc.model.IpcEnvelop envelop = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.spring.up.ipc.model.IpcEnvelop, io.spring.up.ipc.model.IpcEnvelop.Builder, io.spring.up.ipc.model.IpcEnvelopOrBuilder> 
        getEnvelopFieldBuilder() {
      if (envelopBuilder_ == null) {
        envelopBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.spring.up.ipc.model.IpcEnvelop, io.spring.up.ipc.model.IpcEnvelop.Builder, io.spring.up.ipc.model.IpcEnvelopOrBuilder>(
                getEnvelop(),
                getParentForChildren(),
                isClean());
        envelop_ = null;
      }
      return envelopBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.spring.up.ipc.model.StreamServerResponse)
  }

  // @@protoc_insertion_point(class_scope:io.spring.up.ipc.model.StreamServerResponse)
  private static final io.spring.up.ipc.model.StreamServerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.spring.up.ipc.model.StreamServerResponse();
  }

  public static io.spring.up.ipc.model.StreamServerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamServerResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamServerResponse>() {
    @java.lang.Override
    public StreamServerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamServerResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamServerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamServerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.spring.up.ipc.model.StreamServerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

