// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.stream.proto

package io.spring.up.ipc.model;

public final class UpStream {
  private UpStream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_StreamClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_StreamClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_StreamClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_StreamClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_StreamServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_StreamServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_StreamServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_StreamServerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021zero.stream.proto\022\026io.spring.up.ipc.mo" +
      "del\032\017zero.enum.proto\032\021zero.status.proto\032" +
      "\022zero.envelop.proto\"J\n\023StreamClientReque" +
      "st\0223\n\007envelop\030\001 \001(\0132\".io.spring.up.ipc.m" +
      "odel.IpcEnvelop\"/\n\024StreamClientResponse\022" +
      "\027\n\017aggregated_size\030\001 \001(\005\"\274\002\n\023StreamServe" +
      "rRequest\0228\n\rresponse_type\030\001 \001(\0162!.io.spr" +
      "ing.up.ipc.model.em.Format\022?\n\017response_p" +
      "arams\030\002 \003(\0132&.io.spring.up.ipc.model.Res" +
      "ponseParams\0223\n\007envelop\030\003 \001(\0132\".io.spring" +
      ".up.ipc.model.IpcEnvelop\0229\n\talgorithm\030\004 " +
      "\001(\0162&.io.spring.up.ipc.model.em.Compress" +
      "ion\022:\n\017response_status\030\005 \001(\0132!.io.spring" +
      ".up.ipc.model.IpcStatus\"K\n\024StreamServerR" +
      "esponse\0223\n\007envelop\030\001 \001(\0132\".io.spring.up." +
      "ipc.model.IpcEnvelopB$\n\026io.spring.up.ipc" +
      ".modelB\010UpStreamP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.spring.up.ipc.model.em.UpEnum.getDescriptor(),
          io.spring.up.ipc.model.UpStatus.getDescriptor(),
          io.spring.up.ipc.model.UpEnvelop.getDescriptor(),
        });
    internal_static_io_spring_up_ipc_model_StreamClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_spring_up_ipc_model_StreamClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_StreamClientRequest_descriptor,
        new java.lang.String[] { "Envelop", });
    internal_static_io_spring_up_ipc_model_StreamClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_spring_up_ipc_model_StreamClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_StreamClientResponse_descriptor,
        new java.lang.String[] { "AggregatedSize", });
    internal_static_io_spring_up_ipc_model_StreamServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_spring_up_ipc_model_StreamServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_StreamServerRequest_descriptor,
        new java.lang.String[] { "ResponseType", "ResponseParams", "Envelop", "Algorithm", "ResponseStatus", });
    internal_static_io_spring_up_ipc_model_StreamServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_spring_up_ipc_model_StreamServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_StreamServerResponse_descriptor,
        new java.lang.String[] { "Envelop", });
    io.spring.up.ipc.model.em.UpEnum.getDescriptor();
    io.spring.up.ipc.model.UpStatus.getDescriptor();
    io.spring.up.ipc.model.UpEnvelop.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
