// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.status.proto

package io.spring.up.ipc.model;

public final class UpStatus {
  private UpStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_IpcStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_IpcStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_RetryParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_RetryParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_RetryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_RetryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_spring_up_ipc_model_ResponseParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_spring_up_ipc_model_ResponseParams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021zero.status.proto\022\026io.spring.up.ipc.mo" +
      "del\"*\n\tIpcStatus\022\014\n\004code\030\001 \001(\005\022\017\n\007messag" +
      "e\030\002 \001(\t\"$\n\013RetryParams\022\025\n\rmax_reconnect\030" +
      "\001 \001(\005\"/\n\tRetryInfo\022\016\n\006passed\030\001 \001(\010\022\022\n\nba" +
      "ckoff_ms\030\002 \003(\005\"3\n\016ResponseParams\022\014\n\004size" +
      "\030\001 \001(\005\022\023\n\013interval_us\030\002 \001(\005B$\n\026io.spring" +
      ".up.ipc.modelB\010UpStatusP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_spring_up_ipc_model_IpcStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_spring_up_ipc_model_IpcStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_IpcStatus_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_io_spring_up_ipc_model_RetryParams_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_spring_up_ipc_model_RetryParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_RetryParams_descriptor,
        new java.lang.String[] { "MaxReconnect", });
    internal_static_io_spring_up_ipc_model_RetryInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_spring_up_ipc_model_RetryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_RetryInfo_descriptor,
        new java.lang.String[] { "Passed", "BackoffMs", });
    internal_static_io_spring_up_ipc_model_ResponseParams_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_spring_up_ipc_model_ResponseParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_spring_up_ipc_model_ResponseParams_descriptor,
        new java.lang.String[] { "Size", "IntervalUs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
