// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zero.enum.proto

package io.spring.up.ipc.model.em;

public final class UpEnum {
  private UpEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017zero.enum.proto\022\031io.spring.up.ipc.mode" +
      "l.em*.\n\013Compression\022\010\n\004NONE\020\000\022\010\n\004GZIP\020\001\022" +
      "\013\n\007DEFLATE\020\002*\'\n\006Format\022\n\n\006BINARY\020\000\022\010\n\004JS" +
      "ON\020\001\022\007\n\003XML\020\002*<\n\010Category\022\020\n\014COMPRESSABL" +
      "E\020\000\022\022\n\016UNCOMPRESSABLE\020\001\022\n\n\006RANDOM\020\002B%\n\031i" +
      "o.spring.up.ipc.model.emB\006UpEnumP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
